# Generated by Django 4.2.3 on 2023-07-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
