# Generated by Django 4.2.3 on 2023-07-14 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "회원", "verbose_name_plural": "회원 리스트"},
        ),
    ]
